### ISSUE TITLE
demo 无法启动

### ISSUE THREAD

**Issue by hshq** [sumory/lor#108]
报错如下：
execute: nginx  -g "env LOR_ENV=dev;" -p `pwd`/ -c conf/nginx-dev.conf
nginx: [emerg] unknown directive "lua_package_path" in .../lor-master/lor_demo/conf/nginx-dev.conf:16
ERROR: Could not start app on port 8888

使用 openresty 命令替换 nginx 后成功：
execute: openresty  -g "env LOR_ENV=dev;" -p `pwd`/ -c conf/nginx-dev.conf
app in dev was succesfully started on port 8888

**Comment by ms2008** [comment]
我记得老版本的 openresty，并没有 openresty 软链，所以启动脚本就用了 nginx。实际上这里的 nignx 就应该是 openresty 否则就会报错。为了保持兼容性，建议还是根据自身需求来修改吧
