### ISSUE TITLE
nginx启动出现cordump

### ISSUE THREAD

**Issue by michaellincn** [sumory/lor#20]
使用demo示例 nginx启动出现cordump

/data/corefile/core_nginx_1478829514.843 
GNU gdb 6.6
Copyright (C) 2006 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "x86_64-suse-linux"...
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/local/openresty/nginx/sbin/nginx'.
Program terminated with signal 8, Arithmetic exception.
#0  0x00002acb9e8c980f in _start () at rtld.c:784
784     rtld.c: No such file or directory.
        in rtld.c
(gdb) bt
#0  0x00002acb9e8c980f in _start () at rtld.c:784
#1  0x00007fff0c1e3e4f in ?? ()
#2  0x000000000000000

操作系统 suse  10.1 64位  内核版本 2.6.16.60-0.21

openresty 版本
resty 0.12
nginx version: openresty/1.9.15.1
built by gcc 4.1.2 20070115 (prerelease) (SUSE Linux)
built with OpenSSL 1.0.2j  26 Sep 2016
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt=-O2 --add-module=../ngx_devel_kit-0.3.0 --add-module=../echo-nginx-module-0.59 --add-module=../xss-nginx-module-0.05 --add-module=../ngx_coolkit-0.2rc3 --add-module=../set-misc-nginx-module-0.30 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.05 --add-module=../srcache-nginx-module-0.31 --add-module=../ngx_lua-0.10.5 --add-module=../ngx_lua_upstream-0.05 --add-module=../headers-more-nginx-module-0.30 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.17 --add-module=../redis2-nginx-module-0.13 --add-module=../redis-nginx-module-0.3.7 --add-module=../rds-json-nginx-module-0.14 --add-module=../rds-csv-nginx-module-0.07 --with-ld-opt=-Wl,-rpath,/usr/local/openresty/luajit/lib --with-pcre=/data/michaellin/tool/pcre-8.35 --with-openssl=/data/michaellin/tool/openssl-1.0.2j --with-http_ssl_module

**Comment by sumory** [comment]
你先用最简单的方式排除是否是你系统本身或者你安装OpenResty的问题

**Comment by michaellincn** [comment]
不好意思，提交错地方，是luastar框架出现问题
