### ISSUE TITLE
当出现这种情况的时候

### ISSUE THREAD

**Issue by icowan** [sumory/lor#28]
```
execute: nginx  -g "env LOR_ENV=dev;" -p `pwd`/ -c conf/nginx-dev.conf
nginx: [emerg] unknown directive "lua_package_path" in /var/www/
```

应该使用修改 start.sh 这个文件:
把 `nginx -p `pwd`/ -c conf/nginx-${PROFILE}.conf`
改成 `openresty -p `pwd`/ -c conf/nginx-${PROFILE}.conf`

**Comment by sumory** [comment]
这是属于配置问题，请自己维护启动/关闭脚本

**Comment by jingb** [comment]
@icowan  我也遇到这个问题了  找了好久才找到你这里来  
可以说下原因嘛   哪怕lua_package_path里的配置都是对的
