### ISSUE TITLE
stack traceback print while processing request

### ISSUE THREAD

**Issue by Gerrard-YNWA** [sumory/lor#30]
Hello:
I want to get some debug info from nginx log file,  especially the lua stack traceback.  However the handling function runs under the 'xpcall' protection.
I tried to opened the debug mode of lor in my app:
```lua
local app = lor({debug = true})
```
but got the errors as follows:
```
[error] 11080#0: *7282 lua entry thread aborted: runtime error: ./lor/lib/debug.lua:20: bad argument #2 to 'print' (string, number, boolean, or nil expected, got table)
```
It is seemed lor's debug mode is uesd for busted
```lua                               
    debug("handle_request:call error", ok, e, ee) 
```

Can lor supports the trackback info in nginx log via ngx.log api like this:

lor/lib/router/layer.lua, line 124.
```lua
if not ok then
    debug("handle_request:call error", ok, e, ee)
    ngx.log(ngx.ERR, "handle_request:call error", ok, e, ee)
    next(e or ee)
end
```
Thanks!

**Comment by sumory** [comment]
`debug` function is designed for development purpose.

for this use case, you're recommended to `print` the error stack on `error middleware` which could be defined at the end of middlewares like this:

```lua
app:erroruse(function(err, req, res, next)
	ngx.log(ngx.ERR, err) -- this `err` is the param of `next(e or ee)` function
end)
```

**Comment by Gerrard-YNWA** [comment]
Thanks for your reply and that perfectly solved my problem.
