### ISSUE TITLE
perf issue ?

### ISSUE THREAD

**Issue by lduboeuf** [sumory/lor#41]
hello,
i've just benchmarked a bare `OpenResty` and `Lor` "Hello World" (generated by `lord new`) with same worker/ max  connection config.  I've found a nearly 10x times request/sec difference between them. Any idea ?

**Comment by sumory** [comment]
Generally, `lor` is not as fast as OpenResty/Nginx when handling requests. 

some reasons listed as follows:

- `URI` are organized as a `trie` tree(the router mechanism) in lor.
- when a request coming, lor will try to find the node  that is adapted to it from this `trie`. 
- and then an `execution pipeline` which contains all matched functions and middlewares will be generated.
- then lor will execute this pipeline to the end
- any error occurs in this pipeline will turn into the `error pipeline` which is similar to the `execution pipeline`

all these processes could slow down  the `hello world` case.

- lor is powerful for business logic like some other frameworks do(such as [express](https://github.com/expressjs/express)) , however it's also a tradeoff with lower performance.
- it's hard to design a meaningful and reasonable test case cause `lor` will process several steps while OpenResty/Nginx only performs `ngx.say("hello world")`.

the current version lor v0.3.0 was refactored for functionality & backward compatibility a few days ago. performance is not the primary of this version. 

without doubt, more jobs need to be done to improve lor's performance and i also need help about this issue. 😃

**Comment by lduboeuf** [comment]
I agree that my benchmark is not equally designed. And I understand that performance it is not a high priority for now ;-) . Anyway you did nice job. Very easy to install and easy to understand.
Not sure for now that i will have the level to help you trough performance concerns though ;-)
