### ISSUE TITLE
little problem

### ISSUE THREAD

**Issue by weichangdong** [sumory/lor#60]
` 
lua entry thread aborted: runtime error: /usr/local/lor/lor/lib/request.lua:17: bad argument #1 to 'sfind' (string expected, got table)
stack traceback:
coroutine 0:
        [C]: in function 'sfind'
        /usr/local/lor/lor/lib/request.lua:17: in function 'new'
        /usr/local/lor/lor/lib/application.lua:37: in function 'run'
`

**Comment by weichangdong** [comment]
`lord  -v
0.3.2`
`/usr/local/openresty/nginx/sbin/nginx  -v
nginx version: openresty/1.11.2.4`

**Comment by ms2008** [comment]
You have specified multiple `Content-Type` headers in single request, which not legal. 

Sure, patch welcome. Something about duplicate headers being concatenated back into one.
