### ISSUE TITLE
需求:多个中间件挂载到所有路由中,但中间件有执行顺序上的要求,如何实现?

### ISSUE THREAD

**Issue by lubocheng** [sumory/lor#63]
比如我想实现先执行白名单读取,再判断权限,这两个中间件挂载到所有路由上且有执行顺序要求,多级处理函数并不能满足需求吧..

**Comment by sumory** [comment]
你这个需求应该使用[app:use](http://lor.sumory.com/api/#app-use-path-middleware-nbsp) API，而不是”多级处理函数“

**Comment by lubocheng** [comment]
app：use是组路由，里面的子路由并没有执行顺序上的区别啊，而且我这两个中间件a,b都是作用在/，都是get请求，目前测试执行顺序固定是a-->b，不知道框架细节是怎么实现的，根据文件名hash？？我想要b-->a这种执行顺序，感觉多级处理函数应该满足，不过要写多个post，get之类的注册下

**Comment by lubocheng** [comment]
app:use支持1-2个参数，现在要作用到所有路由，省略第一个参数，填上2个中间件，肯定不行啊，语法错误   用app:get("/",fun1,fu2,fun3）也不行，这样只会作用到“/"，不会作用到所有路由啊，省略路由后多个func也会语法错误

**Comment by sumory** [comment]
`app:use(func1, func2, func3)`会在所有路由上起作用，顺序为func1、func2、func3

**Comment by lubocheng** [comment]
做了如下尝试，不行啊：
```lua
a = function(req, res, next)
    ngx.say("haha")
end
b = function(req, res, next)
    ngx.say("hehe")
end
app:use(a, b)
```

**Comment by lubocheng** [comment]
另外，大哥，还有个问题，app:erroruse中错误处理插件(middleware)的参数是function(err, req, res, next) end吧，但是ngx.log打出来的日志中server老是空，没有获取到？：
错误信息xxx， client：xxx, server：（总是空的）, requrest：xxx

**Comment by sumory** [comment]
我看了下API，目前app:use不支持`app:use(middleware1,middleware2)`这种写法，对于你的以上需求，我写了个简单的小例子，你可以参考：
```lua
    app:get("/test/2", function(req, res, next)
        res:send("test2.")
    end)

    app:get("/test/1", function(req, res, next)
        res:send("test1.")
    end)
    
    -- 作用于所有请求
    app:use(function(req, res, next)
        ngx.log(ngx.ERR, "all middleware 1")
        next()    
    end)
    app:use(function(req, res, next)
        ngx.log(ngx.ERR, "all middleware 2")
        next()
    end)

    -- 作用于URI以/test开头的请求
    app:use("/test", function(req, res, next)
        ngx.log(ngx.ERR, "test middleware 1")
        next()
    end)
    app:use("/test", function(req, res, next) 
        ngx.log(ngx.ERR, "test middleware 2")
        next()
    end)
```
如上，这时访问`/test/1`或`/test/2`，将依次打印
```
all middleware 1
all middleware 2
test middleware 1
test middleware 2
```

**Comment by sumory** [comment]
app:use的用法具体参看文档：http://lor.sumory.com/api/#app-use-path-middleware-nbsp
