### ISSUE TITLE
多个中间件有执行顺序的要求，当某个中间件含有多个next()时,执行顺序有问题

### ISSUE THREAD

**Issue by lubocheng** [sumory/lor#64]
```lua
    -- 作用于所有请求
    app:use(function(req, res, next)
        ngx.log(ngx.ERR, "all middleware 1")
       local a = xxx
       if a then
         next()
       end
        next()    
    end)
    app:use(function(req, res, next)
        ngx.log(ngx.ERR, "all middleware 2")
        next()
    end)
```
问题如上:期望是先执行middleware 1,后执行2,当middleware 的变量a为ture时,执行顺序会是1--2--1,即middleware 被执行了多次,如何避免这种情况?尝试a为true时return,刷新页面有下载行为,不知道为什么

**Comment by sumory** [comment]
a=true时，代码上的意图就是执行**两次**，这个表现符合预期。你这属于`next`误用，请先理解next语义：即继续执行下一个处理中间件。我理解你其实是想实现当a为true时放弃执行后面的逻辑？那应该这么写：

```lua
    app:use(function(req, res, next)
       ngx.log(ngx.ERR, "all middleware 1")
       local a = true
       if a then
            next()
       else
            res:send("a is not true")
       end
    end)
    app:use(function(req, res, next)
        ngx.log(ngx.ERR, "all middleware 2")
        next()
    end)
```

> 尝试a为true时return, 刷新页面有下载行为

什么叫“return”？另外`刷新页面有下载行为`属于客户端问题，可能是由于不同浏览器对不同的http响应内容默认解析不同，有的理解为下载，这并不属于lor的讨论范畴。

**Comment by lubocheng** [comment]
出现浏览器下载行为的原因: 在middleware中出现return语句, 中间件不能通过return跳过执行啊
另:
我的中间件有两个,1是读取白名单,2是校验权限 
1中出现多个next的情况是因为白名单从文件读取,但又希望只在文件修改的时候读取,于是有了:
情况1: 中间件1---文件未改变--next()--2
情况2: 中间件1---文件改变--继续执行1后面的代码--next()---2
没想到当出现情况1时,执行完中间件2,又会继续执行情况2,也就是中间间含有多个next会来回执行,可我的情况又必须要多个next...所以很伤脑筋..很无助...看来我这个需求没法搞

**Comment by sumory** [comment]
这算是业务需求了，你梳理下吧，框架不负责解决具体的业务场景，不然就不够通用了。
