### ISSUE TITLE
建议把reload.sh里的-s reload的方式替换为kill -HUP `cat tmp/dev-nginx.pid`

### ISSUE THREAD

**Issue by tweyseo** [sumory/lor#66]
今天测试cosocket的连接池的时候发现修改lua_code_cache off/on,然后使用reload的时候,cosocket连接池不会跟着新的lua VM走.也就是cosocket应该是跟lua VM绑定的,lua_code_cache off的时候,cosocket连接池会跟着具有单次请求生命期的lua VM一起销毁,这种情况下抓包也确实证明了这一点,但是当修改lua_code_cache on并且reload的时候,抓包**发现cosocket连接池还是同样只具有单次请求的生命期**;而结束进程,保持lua_code_cache on的情况下重新启动,cosocket连接池却是正常的全局lua VM的生命期.上述测试中把reload的方式替换为kill -HUP `cat tmp/dev-nginx.pid`,这个时候抓包发现,cosocket连接池能够正常的切换到全局的lua VM,而且查阅资料,春哥和NGX官方都有提到"-s reload的引入主要是为了支持Windows 系统,在UNIX风格的系统上可以基本工作,但容易引起一些问题.",所以建议建议把reload.sh里的-s reload的方式替换为kill -HUP `cat tmp/dev-nginx.pid`.
发出来之前最后一次测试,发现-s reload还会再次调用init_by_lua,这个对于在这里初始化一些全局变量的做法应该是伤害挺大的吧.

**Comment by sumory** [comment]
可否直接提一个pr？:)

**Comment by ms2008** [comment]
其实 `reload` 就是 `SIGHUP`，不过 `nginx -s` 会 fork 一个新进程出来，然后这个进程接着再给 master 发送对应信号

另外参考 nginx 官方提供的启动脚本来看 [/ecc/init.d/nginx](https://www.nginx.com/resources/wiki/start/topics/examples/redhatnginxinit/)：

```sh
reload() {
    configtest || return $?
    echo -n $"Reloading $prog: "
    killproc $nginx -HUP
    RETVAL=$?
    echo
}
```

确实用的是 `kill -HUP`，应该是更为推荐的。
