### ISSUE TITLE
如何debug？

### ISSUE THREAD

**Issue by AndsonYe** [sumory/lor#7]
请教一下，如果想在router里面打印一些调试信息要如何做呢？
尝试过用ngx.log但是并没有打印出来，也没输出到日志。

**Comment by sumory** [comment]
ngx.log是可以的，你再试下

**Comment by AndsonYe** [comment]
恩恩可以了。刚才是日志输出level没设置好。

**Comment by AndsonYe** [comment]
还有个问题，例如如果想看openresty-china里的db.lua里面的打印信息，要怎么看呢？

**Comment by sumory** [comment]
如果实在运行时状态，只能通过ngx.log/ngx.say这样的方式打印了
