### ISSUE TITLE
/usr/bin/env: ‘resty’: No such file or directory

### ISSUE THREAD

**Issue by tcrct** [sumory/lor#70]
在安装lor时，执行lord path后报这个异常，我找遍了openresty都没发现有resty之个目录，反而在lor_master（下载的源文件目录）及/usr/local/lor下找到一个resty目录，添加到环境变量后依家不行。

我的openresty版本是：nginx version: openresty/1.13.6.1

在openresty目录 下没找到resty目录

**Comment by mikewu86** [comment]
sudo ln -s /usr/local/openresty/bin/resty /usr/bin/resty

**Comment by sumit480** [comment]
Thank you @mikewu86 ,it helped.
