### ISSUE TITLE
请教lor时的一个用户验证的方法

### ISSUE THREAD

**Issue by mikewu86** [sumory/lor#71]
hi，请教一个问题。
我在验证用户的合法性之后，会生成一个token下发，服务端通过redis管理该token。
现在我需要所有的客户端请求过来，都验证一下token。
请问有没有办法在所有请求之前做一个判断呢？

return function(app)
    app:get("/test1", function(req, res, next)
        res:send("hello world")
    end)
    app:get("/test1", function(req, res, next)
        res:send("hello world")
    end)
end

如上述代码，我需要判断/signin之外的所有get请求的token，请问可有在每个get代码块里面去检查之外（重复代码很多，单独出来一个函数每次调用也不美观），可有更好的写法？

**Comment by mikewu86** [comment]
自己回复，使用多级处理函数可以解决。。。

**Comment by sumory** [comment]
活用middleware机制，可以实现非常多的类似需求，官网的文档可以多看看
