### ISSUE TITLE
使用XMLHttpRequest，POST数据，结果服务端收到OPTIONS方法。出错了

### ISSUE THREAD

**Issue by hanyu363** [sumory/lor#73]
2018/03/20 07:10:48 [error] 10#10: *1 [lua] server.lua:25: func(): Oh! no handler to process method: options, client: 114.225.31.232, server: , request: "OPTIONS /account/login HTTP/1.1", host: "passport.hog16.com", referrer: "http://localhost:7456/"

**Comment by sumory** [comment]
ajax发起POST类请求我一直在用，未出现你说的这种问题

**Comment by cloudfreexiao** [comment]
@hanyu363  我也出现了这个 问题 用的是 axios post 请问 你解决了吗

**Comment by cloudfreexiao** [comment]
我用 postman 就没问题。
很尴尬

**Comment by linsir** [comment]
前端构架在请求接口时，会先用`OPTIONS`去探测。这里报这个错，是因为路由里没定义`OPTIONS`方法。
