### ISSUE TITLE
运行lord生成的项目nginx报session_aes_key的错误

### ISSUE THREAD

**Issue by liwangmj** [sumory/lor#77]
2018/06/15 21:52:27 [error] 50#50: *2 [lua] session.lua:54: mw_session(): session_aes_key and session_aes_secret should be set for session middleware, client: 58.101.216.2, server: api.liwangmj.com, request: "GET / HTTP/2.0", host: "api.liwangmj.com"
2018/06/15 21:52:27 [error] 50#50: *2 [lua] server.lua:37: func(): session_aes_key and session_aes_secret should be set for session middleware, client: 58.101.216.2, server: api.liwangmj.com, request: "GET / HTTP/2.0", host: "api.liwangmj.com"

**Comment by sumory** [comment]
提示指明了，需要配置session_aes_key和session_aes_secret
