### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by AndsonYe** [sumory/lor#8]
Hi, 
我正在用lor参照openresty-china的例子写一个server，我想用lor实现用户登陆和认证，然后保持我之前后台的application server不变，认证成功之后把http请求转给后台的app server，实现之前在nginx里的 
proxy_pass http://localhost:7000;

我现在的做法是在lua部分认证成功后用res:redirect, router部分代码如下：
local lor = require("lor.index")
local painter_router = lor:Router()

painter_router:post("/upload", function(req, res, next)
    ngx.log(ngx.DEBUG, "redirecting upload...")
    return res:redirect("/Tornado/upload")
end)

return painter_router
在router处理这部分之前有 app:use(check_login_middleware(whitelist))，跟openresty-china中的类似。

相应的nginx.conf的部分是
location /Tornado {
                internal;
                proxy_pass http://localhost:7000;
            }

这样做遇到两个问题：
1. 是如果我把这个location设置为internal，将返回404 not found，但是我不想把这个接口暴露出来，因为是需要认证成功之后才能使用的；
2. 是如果去掉internal，后台可以收到请求，但是请求类型变成了GET而不是原来的POST。

请问怎么可以做到认证成功后作为代理将请求转发给后台的app server处理，而且不把后台暴露出来呢？

谢谢！

**Comment by sumory** [comment]
对于问题1. res:redirect就是用于Get请求的。

你的想法是想做一个控制层，然后代理后端已经有的服务？如果是这样的话，我建议你参看[orange](https://github.com/sumory/orange)的“分流”插件，你也可以自己实现，大概设计如下：

 `location /`匹配所有流量，然后在access_by_lua阶段的代码里做权限验证，如果授权失败直接ngx.exit(403)之类的状态码，如果成功则应该设置一个proxy，然后通过nginx的proxy_pass指令代理到后端upstream，当然这个后端的upstream就是可以隐藏的了。

**Comment by AndsonYe** [comment]
我是想用lor做一个用户账户管理的控制层，其实主要就是用openresty-china里面的check_login中间件和auth.lua路由，验证身份通过后想把请求交给隐藏的upstream处理。直接在access_by_lua_block里实现的应该是适合一些判断ip和url的简单操作吧？

**Comment by sumory** [comment]
access_by_lua常用来过鉴权处理，这个阶段已经能拿到你想要的http请求参数了，过了这个阶段才是proxy处理或是后续的content_by_lua阶段。

lor项目适合运行在content_by_lua阶段，它的所有API都是适配这个阶段的。当然你也可以使用在access_by_lua阶段，但一些API就不是那么灵活了，这时候，你可以直接使用ngx对象。

针对你的需求，也可以使用lor做一层薄的“鉴权处理”，然后交由后续的upstream，但不能使用`res`对象的方法了，因为res对象包装了ngx.say/ngx.exit/ngx.redirect之类的API，对你的需求来说不太灵活。你可以直接使用ngx对象的方法来操作。

**Comment by AndsonYe** [comment]
用ngx.exec在painter_router里实现了想要的结果。

**Comment by AndsonYe** [comment]
还有一个trivial的问题，为什么每次运行lord start的时候都会有CERROR: Could not start app on port 8888
即使我在nginx.conf里改了端口它也会提示8888，而且server成功起来了

**Comment by sumory** [comment]
是你之前启用过nginx没有杀掉吧，查看下8888是不是被占用了或者旧的lor进程没有杀掉
