### ISSUE TITLE
trie.lua第75行有bug

### ISSUE THREAD

**Issue by eyehere** [sumory/lor#82]
https://github.com/sumory/lor/blob/master/lib/lor/lib/trie.lua

`name = string_sub(name, 1, index-1 )`
改成：
`name = string_sub(name, 1, index-2 )`

可能用的人少没发现？
例如：
```lua
userRouter:get("/query/:id/:retest%(0-9)", function(req, res, next)
    res:send(utils.json_encode(req.params))
end)
```

**Comment by sumory** [comment]
麻烦补个pr和单测 😃

**Comment by ms2008** [comment]
我认为有问题的地方不是在这里，这么改反而弄错了。

https://github.com/sumory/lor/blob/a9be51826d858018095e49a9688eb37c45ce6c82/lib/lor/lib/trie.lua#L70-L81

这一段的主要作用是提取命名参数中的正则，L71 取得是 `(` 的起始位置，而不是 `%(` 的位置。而 `name` 取得就是 `params`。

> `string.find` 默认匹配的是 pattern，而不是 string。

这里的正则用的是 Lua 的 pattern，而不是传统的 regex，正因为如此，lor 允许 uri 中出现 `%`。比如：

```
假设有路由 /:uid(%d)

请求 /foo 时，不会比配
请求 /123 时，req.params 的结果就是 {"uid":"123"}
```

回到你的例子：

```lua
userRouter:get("/query/:id/:retest%(0-9)", function(req, res, next)
    res:send(utils.json_encode(req.params))
end)
```

lor 会认为你的 `params` 是 `retest%` 而不是 `retest`，`0-9` 不会被认为是数字匹配，而仅仅是 `0-9` 字符串。所以理论上，只有 `/query/foo/0-9` 这样的请求才会被捕获，而此时 `req.params` 的期待结果将是 `{"retest%":"0-9","id":"foo"}`。但是实际上这里会 500，真正的原因在于这里：
    
https://github.com/sumory/lor/blob/a9be51826d858018095e49a9688eb37c45ce6c82/lib/lor/lib/trie.lua#L23

这里需要将 `%` 转义为 `%%`

如果按照你的改法的话，上面那个例子就会变成这样

```
假设有路由 /:uid(%d)

请求 /foo 时，不会比配
请求 /123 时，req.params 的结果就是 {"ui":"123"}
```

**Comment by ms2008** [comment]
麻烦 @sumory 饭总确认下😄

**Comment by Hamvorinf** [comment]
为何我一直收到这个项目的邮件？我从未关注过这个项目

**Comment by sumory** [comment]
是这样的
