### ISSUE TITLE
post大数据丢失问题

### ISSUE THREAD

**Issue by lcstore** [sumory/lor#84]
post方法在其他框架上是正常work的，引入lor之后，post的数量达到content-length":"44023"时，接收到的req.body=nil, 减少数据可以正常post。请问这个问题是哪里限制了数据量吗？

环境信息：
opm list lor：
sumory/lor 0.3.3

**Comment by lcstore** [comment]
lor/lib/lor/lib/request.lua 这个类中，读取请求体相关代码存在问题：
1）请求体小于client_body_buffer_size，读取请求体代码：
 local json_str = ngx.req.get_body_data()
2）请求体的size大于nginx配置里的client_body_buffer_size，则会导致请求体被缓冲到磁盘临时文件里，client_body_buffer_size默认是8k或者16k。
  local datafile = ngx.req.get_body_file()
      
lor/lib/lor/lib/request.lua的代码没覆盖到2）的情况

**Comment by lcstore** [comment]
@sumory  帮忙看看呢

**Comment by ms2008** [comment]
request body 太大了，不介意 lor 去直接读文件，or 读文件的操作都是阻塞的，建议根据你的需求调大 `client_body_buffer_size ` 的大小

**Comment by lcstore** [comment]
嗯，调大client_body_buffer_size是一种解决的办法，不过请求体慢慢增大可能就丢失数据了。
