### ISSUE TITLE
request body 太大了，不建议 lor 去直接读文件，or 读文件的操作都是阻塞的，建议根据你的需求调大 `client_body_buffer_size ` 的大小

### ISSUE THREAD

**Issue by hzgoin** [sumory/lor#88]
request body 太大了，不建议 lor 去直接读文件，or 读文件的操作都是阻塞的，建议根据你的需求调大 `client_body_buffer_size ` 的大小

_Originally posted by @ms2008 in https://github.com/sumory/lor/issues/84#issuecomment-453969209_

请问是否可以考虑增加ngx.req.get_body_file()的逻辑，考虑到这个逻辑跟调整client_body_buffer_size不会冲突。
1.增加了这个逻辑后，不会出现req.body莫名为nil的问题。初次碰见这个问题时，不会第一时间想到lor框架中没有get_body_file()，debug费了好些时间，尤其开发测试环境跟线上并发和数据量有较大差异时（当然也有测试的不到位的问题）
2.增加这个逻辑之后，开发者依然可以根据自己选择来调整client_body_buffer_size来优化post请求

**Comment by sumory** [comment]
我个人观点还是不建议通过lor去做上传；另外，针对你说的这个问题，你看下可以提个pr？

**Comment by hzgoin** [comment]
我是通过middleware给req增加了get_client_body_file函数，然后在body可能超过buffer size的地方主动判断调用，以获取临时文件中的body内容

`local req_plugin = require("middleware.req_plugin")
app:use(req_plugin())`

----middleware/req_plugin.lua----代码参考自《openresty最佳实践》中[获取请求body](https://moonbingbing.gitbooks.io/openresty-best-practices/openresty/get_req_body.html)一节的代码
`local getFile = function(file_name)
    local f = assert(io.open(file_name, "r"))
    local string = f:read("*all")
    f:close()
    return string
end
return function()
    return function(req, res, next)
        req.get_client_body_file = function(self)
            local file_name = ngx.req.get_body_file()
            if file_name then
                return getFile(file_name)
            end
        end
        next()
    end
end`
