### ISSUE TITLE
执行命令报错

### ISSUE THREAD

**Issue by liuziying** [sumory/lor#89]
# lord -v
2019/05/22 00:37:42 [warn] 12628#12628: *2 [lua] _G write guard:12: __newindex(): writing a global lua variable ('new_handler') which may lead to race conditions between concurrent requests, so prefer the use of 'local' variables
stack traceback:
        /usr/local/lor/bin/scaffold/launcher.lua:38: in main chunk
        [C]: in function 'require'
        /usr/local/lor/bin/lord.lua:4: in main chunk
        [C]: in function 'require'
        /usr/local/bin/lord:7: in function 'file_gen'
        init_worker_by_lua:46: in function <init_worker_by_lua:44>
        [C]: in function 'xpcall'
        init_worker_by_lua:53: in function <init_worker_by_lua:51>, context: ngx.timer
0.3.4

**Comment by liuziying** [comment]
有人可以解答一下原因吗

**Comment by ms2008** [comment]
贴一下 openresty 版本，复现步骤

**Comment by lyken** [comment]
系统版本：centos-7.6 64x  nginx version: openresty/1.15.8.1  （通过 yum 安装）多次安装都如此报错，重装系统也一样，只要执行 lord 命令都会出现这个问题

**Comment by lyken** [comment]
> 贴一下 openresty 版本，复现步骤

系统版本：centos-7.6 64x nginx version: openresty/1.15.8.1 （通过 yum 安装）多次安装都如此报错，重装系统也一样，只要执行 lord 命令都会出现这个问题

**Comment by liuziying** [comment]
> 贴一下 openresty 版本，复现步骤

系统版本：centos-7.6 64x nginx version: openresty/1.15.8.1 （通过 yum 安装）多次安装都如此报错，重装系统也一样，只要执行 lord 命令都会出现这个问题

**Comment by ms2008** [comment]
`openresty/1.15.8.1` 是最新的版本，未测试过，可能不太兼容。尝试使用 `openresty/1.13.6.2` 版本

**Comment by tom2nonames** [comment]
只是一个全局变量的警告,可以忽略,不影响使用.

**Comment by ms2008** [comment]
fixed in #91
