### ISSUE TITLE
cygwin环境安装sumory/lor成功后报thread.exdata找不到

### ISSUE THREAD

**Issue by jordon1899** [sumory/lor#94]
有人在cygwin环境安装lor成功过吗？我安装后运行lord -h 报错"nginx: [error] failed to run the Lua code for coroutine.wrap(): 2: coroutine.wrap:2: module 'thread.exdata' not found"，LUAJIT_LIB和LUAJIT_INC已经指向了openresty自带的luajit ，openresty我是用openresty-1.15.8.2.tar.gz 源码安装的，通过修改几个makefile已经安装上了，resty -v 和nginx -v都运行正常

**Comment by jordon1899** [comment]
I resolved this problem by:
1. use cygwin insall setup-x86.exe to uninstall key  "lua" and "luajit" all installed compoments at full mode.
2. recompile and make install the lastly version openresty1.15.8.2 and lor0.3.4

**Comment by ms2008** [comment]
@jordon1899 Thank you for adding the solution to this issue!
