### ISSUE TITLE
019/12/28 11:39:36 [error] 18659#18659: *1580 [lua] session.lua:85: func(): cannot get session_data:no cookie found in the current request

### ISSUE THREAD

**Issue by lifeblood** [sumory/lor#97]
019/12/28 11:39:36 [error] 18659#18659: *1580 [lua] session.lua:85: func(): cannot get session_data:no cookie found in the current request

**Comment by lifeblood** [comment]
return res:render("vest/privacy-policy")

**Comment by lifeblood** [comment]
res:render 读不出文件，这是为什么

**Comment by ms2008** [comment]
从你的报错信息来看，是请求没有带 cookie 信息吧，和 `res:render` 关系不大。

请提供一段最小复现的代码。
